---
- hosts: jumpbox
  gather_facts: false
  roles:
    - tosin2013.kvm_cloud_init_vm
- hosts: master
  gather_facts: false
  roles:
    - tosin2013.kvm_cloud_init_vm
- hosts: nodes
  gather_facts: false
  roles:
    - tosin2013.kvm_cloud_init_vm
- hosts: lb
  gather_facts: false
  roles:
    - tosin2013.kvm_cloud_init_vm
