---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Check that Cockpit is running
    command: systemctl status cockpit
    ignore_errors: true
    register: cockpit_status
  - debug: msg="Cockpit is not running"
    failed_when: "'FAILED' in cockpit_status.stderr"
  - name: Enable service cockpit
    systemd:
      name: cockpit
      enabled: yes
      masked: no
    failed_when: "'FAILED' in cockpit_status.stderr"
  - name: Make sure cockpit service is Active
    systemd:
      state: started
      name: cockpit
    failed_when: "'FAILED' in cockpit_status.stderr"
  - name: enable firewalld for cockpit
    firewalld:
      service: cockpit
      permanent: yes
      state: enabled
    failed_when: "'FAILED' in cockpit_status.stderr"
  - name: Reload firewalld for cockpit access
    command: firewall-cmd --reload
    failed_when: "'FAILED' in cockpit_status.stderr"
