---
- hosts: gluster
  remote_user: "{{ rhel_user }}"
  become: yes
  tasks:
  - name: Enable rh-gluster-3-client-for-rhel-7-server-rpms repository
    rhsm_repository:
      name: rh-gluster-3-client-for-rhel-7-server-rpms
      state: enabled
    when:
      - ansible_distribution == "RedHat"
      - glusterstorage

  - name: Install glusterfs-fuse
    yum:
      name:
        - glusterfs-fuse
    when:
      - ansible_distribution == "RedHat"
      - glusterstorage
  - name: install glusterfs-server packages
    yum:
      name:
        - glusterfs-server
      state: present
    when:
      - ansible_distribution == "CentOS"
      - glusterstorage
