---
- hosts: jumpboxdeploy
  remote_user: "{{ rhel_user }}"
  become: yes
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: install base packages
    yum:
      name:
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      state: present
  - name: Enable a Ansible 2.4 repository
    rhsm_repository:
      name: rhel-7-server-ansible-2.4-rpms
      state: enabled
  - name: Enable rhel-7-server-rpms repository
    rhsm_repository:
      name: rhel-7-server-rpms
      state: enabled
  - name: Enable rhel-7-server-extras-rpms repository
    rhsm_repository:
      name: rhel-7-server-extras-rpms
      state: enabled
  - name: Enable rhel-7-server-optional-rpms repository
    rhsm_repository:
      name: rhel-7-server-optional-rpms
      state: enabled
  - name: Install a list of packages
    yum:
      name:
        - ansible
        - pyOpenSSL
        - docker
        - device-mapper-event-libs
        - device-mapper-libs
        - httpd-tools
        - java-1.8.0-openjdk-devel.x86_64
        - tmux
      state: present
  - name: Cloning OpenShift release-3.9 to machine
    git:
      repo: 'https://github.com/openshift/openshift-ansible.git'
      dest: /home/{{ rhel_user }}/openshift-ansible
      version: release-3.9
  - name: change openshift-ansible owner to {{ rhel_user }}
    file:
      path: /home/{{ rhel_user }}/openshift-ansible
      owner: "{{ rhel_user }}"
      group: "{{ rhel_user }}"
      mode: 0775
  - name: Cloning  Bash full of Colors to machine
    git:
      repo: 'https://github.com/tosin2013/bash-full-of-colors.git'
      dest: /home/{{ rhel_user }}/bash-full-of-colors
  - name: Run script to modifiy terminal layout
    shell: |
      cd /home/{{ rhel_user }}
      [ -f .bashrc ] && mv -v .bashrc /tmp/bashrc.old
      [ -f .bash_profile ] && mv -v .bash_profile /tmp/bash_profile.old
      [ -f .bash_aliases ] && mv -v .bash_aliases /tmp/bash_aliases.old
      [ -f .bash_logout ] && mv -v .bash_logout /tmp/bash_logout.old
      cp /home/{{ rhel_user }}/bash-full-of-colors/bashrc.sh /home/{{ rhel_user }}/.bashrc
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_profile.sh /home/{{ rhel_user }}/.bash_profile
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_aliases.sh /home/{{ rhel_user }}/.bash_aliases
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_logout.sh /home/{{ rhel_user }}/.bash_logout
      rm -rf bash-full-of-colors/
