- hosts: all
  gather_facts: no
  remote_user: "{{ rhel_user }}"
  tasks:
  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 300
