---
- hosts: dns_server
  remote_user: "{{ rhel_user }}"
  become: yes
  gather_facts: false
  tasks:
  - include_vars: dns_key/dns_key
  - name: Add or modify {{ a_record }} A to {{ ip_address }}"
    nsupdate:
      key_name: "example.key"
      key_secret: "{{ vault_dns_key }}"
      server: "0.0.0.0"
      zone: "example.com"
      record: "{{ a_record }}"
      value: "{{ ip_address }}"
