---
- name: deploy DHCP server
  hosts: dhcpserver
  remote_user: admin
  become: true
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  tasks:
    - name: ensure system is registered to Red Hat
      include_role:
        name: swygue-redhat-subscription

    - name: Configure DHCP
      include_role:
        name: ansible-role-dhcp
