- name: Deploy DHCP SERVER VM
  hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  vars:
    vm_name: "{{ dhcp_server_vm.dhcp_name }}"
    vm_cpu: "{{ dhcp_server_vm.dhcp_vm_vcpu }}"
    vm_memory: "{{ dhcp_server_vm.dhcp_vm_memory }}"
    vm_root_disk_size: "{{ dhcp_server_vm.dhcp_vm_root_disk_size }}"
    vm_teardown: "{{ dhcp_server_vm.dhcp_vm_teardown }}"
    vm_recreate: "{{ dhcp_server_vm.dhcp_vm_recreate }}"
    inventory_group: "{{ dhcp_server_vm.dhcp_group }}"
    extra_storage: "{{ dhcp_server_vm.dhcp_extra_storage }}"
    enable: "{{ dhcp_server_vm.dhcp_enable }}"
    dhcp_srv_ip: "{{ hostvars[vm_name]['ansible_host'] }}"

  tasks:
    - name: Create KVM VM for DHCP Server
      include_role:
        name: ansible-role-rhel7-kvm-cloud-init

    - set_fact:
        etc_host_status: "{{ 'absent' if vm_teardown|bool else 'present' }}"

    - name: Add/Remove DHCP server from inventory into /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}.{{ domain }} {{ item }}"
        state: "{{ etc_host_status }}"
      when: hostvars[item]['ansible_host'] is defined and hostvars[item]['inventory_hostname_short'] == vm_name
      with_items:
        - "{{ groups['dhcpserver'] }}"
