- name: deploy all VMs required
  hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: include create vm tasks
      include_tasks: vms_inc.yml
      loop: "{{ instances }}"
      loop_control:
        loop_var: outer_item
        label: outer_item.name
