#- name: create VM for each ocp/okd node role
#  vars:
#    vm_cpu: "{{ outer_item.vm_cpu }}"
#    vm_memory: "{{ outer_item.vm_memory }}"
#    vm_root_disk_size: "{{ outer_item.vm_root_disk_size }}"
#    extra_storage: "{{ outer_item.extra_storage }}"
#    vm_recreate: "{{ outer_item.vm_recreate }}"
#    vm_name: "{{ preappend_host_name}}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
#    vm_teardown: "{{ outer_item.vm_teardown }}"
#    role_group: "{{ outer_item.role_group }}"
#    inventory_group: "{{ role_group }}"
#  include_role:
#    name: ansible-role-rhel7-kvm-cloud-init
#  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
#  loop_control:
#    loop_var: inner_item
#    label: "deploying {{ vm_name }} as a {{ role_group }} node"

- name: update list with each VM created
  vars:
    role_group: "{{ outer_item.role_group }}"
    vm_name: "{{ preappend_host_name}}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
  lineinfile:
    path: "{{ vm_data_dir }}/nodes_list.txt"
    state: present
    regexp: "^{{ vm_name }}"
    line: "{{ vm_name }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "deploying {{ vm_name }} as a {{ role_group }} node"
  when: not vm_teardown|bool 
