---
- name: create nodes dns records
  import_playbook: nodes_dns_records.yml

- name: qbnodes post installation
  hosts: qbnodes:!*.{{domain}}
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: declare post install file for {{ product }}
      set_fact:
        product_postinstall: "{{ 'ocp_nodes_postinstall.yml' if product == 'ocp' else 'okd_nodes_postinstall.yml' }}"
      tags:
        - always

    - name: include post install for product {{ product }}
      include_tasks: "{{ product_postinstall }}"
      tags:
        - always

    - name: update system
      yum:
        name: '*'
        state: latest

    - name: install docker on all noded except the lbs
      yum:
        name: "{{ ocp_gluster_pkg }}"
      when: inventory_hostname not in groups['lbs']

    - name: create docker-storage-setup file
      copy:
        dest: "/etc/sysconfig/docker-storage-setup"
        content: |
          STORAGE_DRIVER=overlay2
          DEVS=/dev/vdb
          VG=docker-vg

    - name: check docker-storage-setup vg
      command: vgdisplay docker-vg
      register: docker_vg
      changed_when: False
      ignore_errors: True
      when: inventory_hostname not in groups['lbs']

    - name: Run docker-storage-setup
      command: docker-storage-setup
      when: docker_vg.rc != 0 and inventory_hostname not in groups['lbs']
      tags: 
        - docker-storage
        - gluster
