---
- name: create nodes dns records
  import_playbook: nodes_dns_records.yml

- name: vm post deployment
  hosts: qbnodes
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: declare post install file for {{ product }}
      set_fact:
        product_postinstall: "{{ 'ocp_nodes_postinstall.yml' if product == 'ocp' else 'okd_nodes_postinstall.yml' }}"
      tags:
        - always

    - name: include post install for product {{ product }}
      include_tasks: "{{ product_postinstall }}"
      tags:
        - always

    - name: install glusterfs-fuse when using gluster storage
      yum:
        name: glusterfs-fuse
      when: glusterfs
      tags: gluster

    - name: install glusterfs-server packages
      yum:
        name:
          - glusterfs-server
        state: present
      tags: gluster
      when: glusterfs and (ansible_hostname in groups['infra'] or
                           ansible_hostname in groups['nodes'])

    - name: update system when required packages are first installed
      yum:
        name: '*'
        state: latest
      when: node_pkgs_install.changed

    - name: create docker-storage-setup file
      copy:
        dest: "/etc/sysconfig/docker-storage-setup"
        content: |
          STORAGE_DRIVER=overlay2
          DEVS=/dev/vdb
          VG=docker-vg
      tags: gluster
      when: glusterfs and (ansible_hostname in groups['infra'] or 
                           ansible_hostname in groups['nodes'] or
                           ansible_hostname in groups['masters'])

    - name: Run docker-storage-setup
      command: docker-storage-setup
      when: glusterfs and (ansible_hostname in groups['infra'] or 
                           ansible_hostname in groups['nodes'] or
                           ansible_hostname in groups['masters'])
      tags: 
        - docker-storage
        - gluster
