- name: vm post deployment
  hosts: qbnodes
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: Generate IPA Session Cookie
      vars:
      uri:
        url: "https://{{ ipa_host }}/ipa/session/login_password"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Accept: "text/plain"
          Referer: "https://{{ ipa_host }}/ipa"
        body: "user={{ idm_admin_user }}&password={{ idm_admin_pwd }}"
      register: ipa_session
      delegate_to: localhost
      tags:
        - dns

    - name: Create A/PTR Records for Master Node
      uri:
        url: "https://{{ ipa_host }}/ipa/session/json"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Cookie: "{{ ipa_session.set_cookie }}"
          Accept: "application/json"
          Referer: "https://{{ ipa_host }}/ipa"
        body:
          method: dnsrecord_add
          params:
          - - "{{ domain }}."
            - "{{ hostvars[item].inventory_hostname }}"
          - a_part_ip_address: "{{ hostvars[item].ansible_host }}"
            a_extra_create_reverse: true
        body_format: json
      when:
        -  "'master'  in hostvars[item].inventory_hostname"
      loop: "{{ groups ['qbnodes'] }}"
      loop_control:
        label: "{{ hostvars[item].inventory_hostname }}"
      delegate_to: localhost


    - pause:
        seconds: 5

    - name: Create A/PTR Records for Infra Nodes
      uri:
        url: "https://{{ ipa_host }}/ipa/session/json"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Cookie: "{{ ipa_session.set_cookie }}"
          Accept: "application/json"
          Referer: "https://{{ ipa_host }}/ipa"
        body:
          method: dnsrecord_add
          params:
          - - "{{ domain }}."
            - "{{ hostvars[item].inventory_hostname }}"
          - a_part_ip_address: "{{ hostvars[item].ansible_host }}"
            a_extra_create_reverse: true
        body_format: json
      when:
        -  "'infra'  in hostvars[item].inventory_hostname"
      loop: "{{ groups ['qbnodes'] }}"
      loop_control:
        label: "{{ hostvars[item].inventory_hostname }}"
      delegate_to: localhost

    - pause:
        seconds: 5

    - name: Create A/PTR Records for App Nodes
      uri:
        url: "https://{{ ipa_host }}/ipa/session/json"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Cookie: "{{ ipa_session.set_cookie }}"
          Accept: "application/json"
          Referer: "https://{{ ipa_host }}/ipa"
        body:
          method: dnsrecord_add
          params:
          - - "{{ domain }}."
            - "{{ hostvars[item].inventory_hostname }}"
          - a_part_ip_address: "{{ hostvars[item].ansible_host }}"
            a_extra_create_reverse: true
        body_format: json
      when:
        -  "'node'  in hostvars[item].inventory_hostname"
      loop: "{{ groups ['qbnodes'] }}"
      loop_control:
        label: "{{ hostvars[item].inventory_hostname }}"
      delegate_to: localhost
      tags:
        - dns

    - name: declare post install file for {{ product }}
      set_fact:
        product_postinstall: "{{ 'ocp_nodes_postinstall.yml' if product == 'ocp' else 'okd_nodes_postinstall.yml' }}"
      tags:
        - always

    - name: include post install for product {{ product }}
      include_tasks: "{{ product_postinstall }}"
      tags:
        - always

    - pause:
        seconds: 5

    - name:  Create Wildcard for Applications
      uri:
        url: "https://{{ ipa_host }}/ipa/session/json"
        validate_certs: no
        method: POST
        status_code: 200
        headers:
          Cookie: "{{ ipa_session.set_cookie }}"
          Accept: "application/json"
          Referer: "https://{{ ipa_host }}/ipa"
        body:
          method: dnsrecord_add
          params:
          - - "{{ domain }}."
            - "{{ dns_wildcard }}"
          - a_part_ip_address: "{{ hostvars[item].ansible_host }}"
            a_extra_create_reverse: false
        body_format: json
      when:
        -  "'infra'  in hostvars[item].inventory_hostname"
      loop: "{{ groups['qbnodes'] }}"
      loop_control:
        label: "{{ hostvars[item].inventory_hostname }}"

    - name: declare which RHSM repos to enable for product {{ product }}
      set_fact:
        product_repos: "{{ ocp_repos if product == 'ocp' else okd_repos }}"

    - name: update system
      yum:
        name: '*'
        state: latest

    - name: install all required packages
      yum:
        name: "{{ pkgs }}"

          VG=docker-vg
      tags: gluster
      when: glusterfs and (ansible_hostname in groups['infra'] or 
                           ansible_hostname in groups['nodes'] or
                           ansible_hostname in groups['masters'])

    - name: Run docker-storage-setup
      command: docker-storage-setup
      when: glusterfs and (ansible_hostname in groups['infra'] or 
                           ansible_hostname in groups['nodes'] or
                           ansible_hostname in groups['masters'])
      tags: 
        - docker-storage
        - gluster

    - name: Enable rh-gluster-3-client-for-rhel-7-server-rpms repository
      rhsm_repository:
        name: rh-gluster-3-client-for-rhel-7-server-rpms
        state: enabled
      when:
        - "'master' not in inventory_hostname"
        - glusterfs

    - name: Install glusterfs-fuse
      yum:
        name:
          - glusterfs-fuse
      when:
        - "'master' not in inventory_hostname"
        - glusterfs

    - name: update hosts file with node ip
      shell: |
          CHECKFORENTRY=$(cat /etc/hosts | grep $HOSTNAME)
          if [[ -z $CHECKFORENTRY ]]; then
            echo "{{ ansible_default_ipv4.address }} $HOSTNAME" >> /etc/hosts
          fi

