---
- name: create nodes dns records
  import_playbook: nodes_dns_records.yml

- name: qbnodes post installation
  hosts: qbnodes:!*.{{domain}}
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: declare post install file for {{ product }}
      set_fact:
        product_postinstall: "{{ 'ocp_nodes_postinstall.yml' if product == 'ocp' else 'okd_nodes_postinstall.yml' }}"
      tags:
        - always

    - name: include post install for product {{ product }}
      include_tasks: "{{ product_postinstall }}"
      tags:
        - always

    - name: update system
      yum:
        name: '*'
        state: latest

    - name: install docker on all noded except the lbs
      yum:
        name: "{{ ocp_gluster_pkg }}"
      when: inventory_hostname not in groups['lbs']

    - name: create docker-storage-setup file
      copy:
        dest: "/etc/sysconfig/docker-storage-setup"
        content: |
          STORAGE_DRIVER=overlay2
          DEVS=/dev/vdb
          VG=docker-vg

    - name: check docker-storage-setup vg
      command: vgdisplay docker-vg
      register: docker_vg
      changed_when: False
      ignore_errors: True
      when: inventory_hostname not in groups['lbs']

    - name: Run docker-storage-setup
      command: docker-storage-setup
      when: inventory_hostname not in groups['lbs'] and docker_vg.rc != 0
      tags:
        - docker-storage
        - gluster

    - name: update ifcfg-eth0 with  loopback for dns
      blockinfile:
        path:  /etc/sysconfig/network-scripts/ifcfg-eth0
        block: |
          PEERDNS=yes
          NM_CONTROLLED=yes

    - name: Reboot immediately if there was a change.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait 60 seconds, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        timeout: 60

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
