---
  - name: Configure OpenShift 4.x deployment Enviornment
    hosts: localhost
    vars_files:
      - vars/all.yml
      - vars/vault.yml
      - vars/idm.yml
      - vars/ocp4.yml
    become: yes

    tasks:
    - name: Download Required images for OpenShift 4.x deployment
      import_role:
        name: swygue.coreos-virt-install-iso
        tasks_from: main.yml
