---
  - name: Configure OpenShift 4.x deployment Enviornment
    hosts: localhost
    vars_files:
      - vars/all.yml
      - vars/vault.yml
<<<<<<< HEAD
      - vars/idm.yml
      - vars/ocp4.yml
=======
>>>>>>> 0cc93945943604a90fac4e8a5ac9101cef4f67e4
    become: yes

    tasks:
    - name: Download Required images for OpenShift 4.x deployment
      import_role:
        name: swygue.coreos-virt-install-iso
        tasks_from: main.yml
