- hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml
    - vars/openshift3_size.yml
  tasks:
  - name: include additional openshift variables
    include_vars: "vars/{{ openshift_product }}.yml"

  - name: obtain the fully qualified domain name of the host
    shell: hostname -f
    ignore_errors: no

  - name: loop through vm types
    include_tasks: openshift3_pre_install_checks_include.yml
    loop: "{{ instances }}"
    loop_control:
      loop_var: outer_item
      label: outer_item.name
