---
- name: Generate Inventory
  hosts: localhost
  become: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml
    - vars/ocp3.yml
  tasks:
    - name: include additional openshift variables
      include_vars: "vars/{{ openshift_product }}.yml"

    - name: include additional openshift variables
      include_vars: "vars/openshift3_size_{{ openshift_deployment_size }}.yml"

    - name: Generating Inventory File
      include_role:
        name: openshift-inventory
