---
- name: setup KVM host
  hosts: localhost
  become: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: ensure host is reigistered to Red Hat
      vars:
        rhsm_user: "{{ rhsm_username | default('') }}"
        rhsm_pass: "{{ rhsm_password | default('') }}"
      include_role:
        name: swygue-redhat-subscription
      when: (openshift_product is defined) and (openshift_product|length == 0) or
            (openshift_pool_id is defined) and (openshift_pool_id|length == 0)

    - name: ensure host is registered to Red Hat and attached to the OpenShift Pool
      vars:
        rhsm_user: "{{ rhsm_username | default('') }}"
        rhsm_pass: "{{ rhsm_password | default('') }}"
        rhsm_pool_ids: "{{ openshift_pool_id | default('') }}"
      include_role:
        name: swygue-redhat-subscription
      when:
        - (openshift_product is defined) and (openshift_product|length > 0)
        - "'ocp' in openshift_product"
        - (openshift_pool_id is defined) and (openshift_pool_id|length > 0)


    - name: create libvirt logical volume
      include_role:
         name: swygue-lvm

    - name: Check whether ifcfg-{{ network_interface_name }} contains "UUID"
      command: grep -Fxq "UUID" /etc/sysconfig/network-scripts/ifcfg-{{ network_interface_name }}
      register: interfacecheck
      check_mode: no
      ignore_errors: yes

    - name: check if ifcfg-{{ network_interface_name }} backup file exists
      stat:
        path: "{{ project_dir }}/backups/ifcfg-{{ network_interface_name }}"
      register: interfacecheck
      delegate_to: 127.0.0.1

    - name: backup  ifcfg-{{ network_interface_name }}
      shell: "cat /etc/sysconfig/network-scripts/ifcfg-{{ network_interface_name }} > {{ project_dir }}/backups/ifcfg-{{ network_interface_name }}"
      when: not interfacecheck.stat.exists
      delegate_to: 127.0.0.1

    - name: running KVM host setup
      include_role:
         name: swygue.edge_host_setup

    - name: validate KVM host setup
      include_role:
         name: edge_hosts_validate
