---
- name: shutdown down kvm instance
  hosts: localhost
  remote_user: admin
  become: true
  vars_files:
    - vars/all.yml
    - vars/vault.yml

  tasks:
    - name: shutdwon kvm instance
      command: /sbin/shutdown -h now
      delegate_to: "{{ vm_name }}"

    - name: wait for vm to shutdown
      local_action: wait_for host={{ vm_name }} port=22 state=stopped
