- name: create virtual machines
  vars:
    vm_cpu: "{{ outer_item.vm_cpu }}"
    vm_memory: "{{ outer_item.vm_memory }}"
    vm_root_disk_size: "{{ outer_item.vm_root_disk_size }}"
    extra_storage: "{{ outer_item.extra_storage }}"
    vm_recreate: "{{ outer_item.vm_recreate }}"
    vm_name: "ocp-{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_teardown: "{{ outer_item.vm_teardown }}"
  include_role:
    name: ansible-role-rhel7-kvm-cloud-init
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "deploying {{ vm_name }}"
